### ISSUE TITLE
Doesn't work with IPFS-JS V0.28.2

### ISSUE THREAD

**Issue by chrismatthieu** [ipfs-shipyard/y-ipfs-connector#13]
In fact, it seems to stop working after version 0.25.x

**Comment by chrismatthieu** [comment]
I noticed that this module depends on ipfs-pubsub-room. Just to be sure, I updated the ipfs-pubsub-room-demo to the latest npm versions and it works fine. Eliminated suspicions of ipfs-pubsub-room being the culprit.

**Comment by chrismatthieu** [comment]
I should also confirm that I am **not** using signing (encrypt/decrypt).

**Comment by pgte** [comment]
@chrismatthieu should be fixed if you reinstalled y-ipfs-connector,  it would upgrade ipfs-pubsub-room from version 1.2.0 to 1.2.1 (see https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/39).

Anyway, I released version 2.2.1 of y-ipfs-connector, which enforces this version. If you upgrade, it should work. Let me know if it doesn't.

**Comment by chrismatthieu** [comment]
Unfortunately, that didn't fix it. Here's my forked repo with the npm updates. I also noticed that YRS uses textarea instead of textfield. I tried both ways but the messages are not being sent to the other browser. https://github.com/chrismatthieu/shared-editing-demo

Thanks for your help. I would like to use y-ipfs-connector in my https://philes.co project.

**Comment by pgte** [comment]
Is there an error being reported?

**Comment by chrismatthieu** [comment]
No errors being reported in the console. I'll try rolling back a few versions of IPFS to see where it breaks.

**Comment by chrismatthieu** [comment]
I tried IPFS v0.27.7 and that doesn't work either. IPFS v0.25.4 previously worked but is not throwing the following error: 

Uncaught Error: no protocol with name: p2p-webrtc-star
    at Protocols (protocols-table.js:17)
    at stringToStringTuples (codec.js:45)
    at stringToBuffer (codec.js:170)
    at Object.fromString (codec.js:178)
    at new Multiaddr (index.js:39)
    at Multiaddr (index.js:27)
    at WebRTCStar._peerDiscovered (index.js:223)
    at Socket.Emitter.emit (index.js:133)
    at Socket.onevent (socket.js:275)
    at Socket.onpacket (socket.js:233)

**Comment by chrismatthieu** [comment]
Perhaps the issue could be related to not having `sourceDir: '/bower_components'` in my config. I'm browserifying the yjs components rather than using bower.
